#!/usr/bin/env python3
"""从 worktree 自动提取算子代码并准备 6 个 PR 文件。

用法:
    python extract_from_worktree.py <op> --repo-dir /path/to/FlagGems
    python extract_from_worktree.py <op> --dry-run  # 只预览不写入

自动完成:
    1. 复制 kernel 文件（确保 KernelGen 首行）
    2. 从 worktree 提取测试函数 → tests/test_<op>.py
    3. 从 worktree 提取 benchmark → benchmark/test_<op>.py
    4. 按字母序插入 ops/__init__.py（import + __all__）
    5. 按字母序插入 __init__.py（_FULL_CONFIG）
    6. 按字母序插入 conf/operators.yaml
"""

import argparse
import ast
import os
import re
import shutil
import sys
import textwrap

import yaml

from op_naming import is_special_op, resolve_op

DEFAULT_REPO = "/data/dxd/FlagGems_minimax_2_7_pr"
KERNELGEN_HEADER = "# Generated by KernelGen: https://github.com/flagos-ai/KernelGen\n"
SPECIAL_MAX_POOL2D_WITH_INDICES_BACKWARD = "max_pool2d_with_indices_backward"


def is_max_pool2d_with_indices_backward(op):
    return op == SPECIAL_MAX_POOL2D_WITH_INDICES_BACKWARD


def ensure_max_pool2d_with_indices_backward_wrapper(content):
    if "def max_pool2d_with_indices_backward" in content:
        return content

    wrapper = '\n\n\ndef max_pool2d_with_indices_backward(\n    grad_output: torch.Tensor,\n    input: torch.Tensor,\n    kernel_size,\n    stride,\n    padding,\n    dilation,\n    ceil_mode,\n    indices: torch.Tensor,\n):\n    logger.debug("GEMS MAX_POOL2D_WITH_INDICES BACKWARD")\n    return max_pool2d_backward(\n        grad_output,\n        input,\n        indices,\n        kernel_size,\n        stride,\n        padding,\n        dilation,\n        ceil_mode,\n    )\n'
    return content.rstrip() + wrapper


def prepare_max_pool2d_with_indices_backward_source(repo):
    """Create a local source fixture from upstream files for this aten alias."""
    worktree = os.path.join(
        repo,
        ".worktrees",
        f"gen-{SPECIAL_MAX_POOL2D_WITH_INDICES_BACKWARD}",
    )
    if os.path.isdir(worktree):
        shutil.rmtree(worktree)

    relpaths = [
        "src/flag_gems/ops/max_pool2d_with_indices.py",
        "src/flag_gems/ops/__init__.py",
        "src/flag_gems/__init__.py",
        "tests/test_max_pool2d.py",
        "benchmark/test_max_pool2d.py",
        "conf/operators.yaml",
    ]
    for rel in relpaths:
        src = os.path.join(repo, rel)
        dst = os.path.join(worktree, rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(src, dst)
    return worktree

# accuracy_utils symbols that need `utils.` prefix when converting imports
UTILS_SYMBOLS = [
    "FLOAT_DTYPES", "ALL_FLOAT_DTYPES", "INT_DTYPES", "ALL_INT_DTYPES",
    "BOOL_TYPES", "COMPLEX_DTYPES", "POINTWISE_SHAPES", "SPECIAL_SHAPES",
    "DISTRIBUTION_SHAPES", "REDUCTION_SHAPES", "to_reference",
    "gems_assert_close", "gems_assert_equal",
]


class Colors:
    OK = "\033[92m"
    FAIL = "\033[91m"
    BOLD = "\033[1m"
    CYAN = "\033[96m"
    END = "\033[0m"


def ok(msg):
    print(f"  {Colors.OK}✓{Colors.END} {msg}")


def warn(msg):
    print(f"  {Colors.CYAN}⚠{Colors.END} {msg}")


def fatal(msg):
    print(f"  {Colors.FAIL}✗ FATAL: {msg}{Colors.END}")
    sys.exit(1)


def section(msg):
    print(f"\n{Colors.BOLD}[{msg}]{Colors.END}")


def get_op_id(op_name):
    return resolve_op(op_name).op_id


def get_module_name(op_name):
    return resolve_op(op_name).module


# ---------------------------------------------------------------------------
# Step 1: Kernel file
# ---------------------------------------------------------------------------


def extract_kernel(op, worktree, repo, dry_run):
    section("Step 1: Kernel 文件")
    module_name = get_module_name(op)
    src = os.path.join(worktree, f"src/flag_gems/ops/{module_name}.py")
    dst = os.path.join(repo, f"src/flag_gems/ops/{module_name}.py")

    if not os.path.isfile(src):
        # Inplace ops (trailing _) may have filename without the underscore
        op_stripped = module_name.rstrip("_")
        alt_src = os.path.join(worktree, f"src/flag_gems/ops/{op_stripped}.py")
        if op_stripped != module_name and os.path.isfile(alt_src):
            src = alt_src
            dst = os.path.join(repo, f"src/flag_gems/ops/{op_stripped}.py")
            warn(f"使用去下划线文件名: {op_stripped}.py")
        else:
            fatal(f"worktree kernel 不存在: {src}")

    with open(src) as f:
        content = f.read()

    if not content.startswith("# Generated by KernelGen"):
        content = KERNELGEN_HEADER + content
    if is_max_pool2d_with_indices_backward(op):
        content = ensure_max_pool2d_with_indices_backward_wrapper(content)
    if not content.endswith("\n"):
        content += "\n"

    if dry_run:
        ok(f"[DRY] 将写入 {dst} ({len(content.splitlines())} 行)")
    else:
        with open(dst, "w") as f:
            f.write(content)
        ok(f"已复制: {dst}")


# ---------------------------------------------------------------------------
# Step 2: Test file
# ---------------------------------------------------------------------------


def find_test_function(op, worktree):
    """Find and extract test function(s) for the operator from worktree.

    Search priority:
    1. test_accuracy_<op_id> — most common pattern
    2. test_accuracy_<op_name> — underscore-prefixed variant
    3. test_<op_id> — no accuracy prefix (reflection_pad3d, embedding etc.)
    4. Any function decorated with @pytest.mark.<op_id>
    """
    tests_dir = os.path.join(worktree, "tests")
    op_id = get_op_id(op)

    candidates = [
        f"test_accuracy_{op_id}",
        f"test_accuracy_{op}" if op.startswith("_") else None,
        f"test_{op_id}",
    ]
    candidates = [c for c in candidates if c]

    for target_func in candidates:
        for fname in os.listdir(tests_dir):
            if not fname.endswith(".py"):
                continue
            fpath = os.path.join(tests_dir, fname)
            with open(fpath) as f:
                content = f.read()
            if f"def {target_func}" in content:
                return fpath, content, target_func

    # Fallback: find by @pytest.mark.<op_id>
    mark_pattern = f"@pytest.mark.{op_id}"
    for fname in os.listdir(tests_dir):
        if not fname.endswith(".py"):
            continue
        fpath = os.path.join(tests_dir, fname)
        with open(fpath) as f:
            content = f.read()
        if mark_pattern in content:
            # Find the first test function after the mark
            match = re.search(rf"{re.escape(mark_pattern)}.*?def\s+(test_\w+)", content, re.DOTALL)
            if match:
                return fpath, content, match.group(1)

    return None, None, None


def find_all_related_test_functions(content, op_id, primary_func_name):
    """Find all test functions related to the operator in the same file.

    Looks for functions decorated with @pytest.mark.<op_id>.
    """
    func_names = []
    mark = f"@pytest.mark.{op_id}"

    # Use regex to find all def lines preceded (somewhere above) by the mark
    # Pattern: @pytest.mark.<op_id> followed eventually by def test_xxx
    for m in re.finditer(
        rf"^{re.escape(mark)}\s*\n(?:.*\n)*?^\s*def\s+(test_\w+)",
        content, re.MULTILINE
    ):
        fn = m.group(1)
        if fn not in func_names:
            func_names.append(fn)

    if not func_names and primary_func_name:
        func_names = [primary_func_name]

    return func_names


def extract_function_block(content, func_name):
    """Extract a function and its decorators from source code."""
    try:
        tree = ast.parse(content)
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                continue
            if node.name != func_name:
                continue
            start = min([d.lineno for d in node.decorator_list] + [node.lineno]) - 1
            end = getattr(node, "end_lineno", None)
            if end is not None:
                return "\n".join(content.split("\n")[start:end])
    except SyntaxError:
        pass

    lines = content.split("\n")
    func_start = None
    decorator_start = None
    func_end = None

    for i, line in enumerate(lines):
        if f"def {func_name}" in line:
            func_start = i
            # Walk backwards to find decorators
            decorator_start = i
            j = i - 1
            while j >= 0:
                stripped = lines[j].strip()
                if stripped.startswith("@") or stripped == "":
                    if stripped.startswith("@"):
                        decorator_start = j
                    j -= 1
                else:
                    break
            break

    if func_start is None:
        return None

    # Find function end (next def/class at same or lower indent, or EOF)
    indent = len(lines[func_start]) - len(lines[func_start].lstrip())
    for i in range(func_start + 1, len(lines)):
        line = lines[i]
        if line.strip() == "":
            continue
        line_indent = len(line) - len(line.lstrip())
        if line_indent <= indent and (line.strip().startswith("def ") or
                                       line.strip().startswith("class ") or
                                       line.strip().startswith("@")):
            # Check if decorator belongs to this function
            if i > func_start + 1:
                func_end = i
                break
    if func_end is None:
        func_end = len(lines)

    # Trim trailing blank lines
    while func_end > decorator_start and lines[func_end - 1].strip() == "":
        func_end -= 1

    return "\n".join(lines[decorator_start:func_end])


def convert_test_imports(func_block, op):
    """Convert direct accuracy_utils imports to `utils.` prefix style."""
    op_id = get_op_id(op)
    result = func_block

    # Replace function name: test_accuracy_<op> → test_<op>
    result = re.sub(rf"def test_accuracy_{re.escape(op_id)}\b",
                    f"def test_{op_id}", result)
    result = re.sub(r"\bdef test_accuracy_", "def test_", result)
    if op.startswith("_"):
        result = re.sub(rf"def test_accuracy_{re.escape(op)}\b",
                        f"def test_{op_id}", result)
        if is_special_op(op):
            def _replace_special_func_name(match):
                suffix = match.group("suffix")
                suffix = f"_{suffix}" if suffix else ""
                return f"def test_{op_id}{suffix}"

            result = re.sub(
                rf"def test_accuracy_{re.escape(op)}(?P<suffix>\w*)\b",
                _replace_special_func_name,
                result,
            )

    # Remove marks that are only meaningful in the monolithic worktree file.
    for mark in resolve_op(op).strip_test_marks:
        result = re.sub(rf"(?m)^@pytest\.mark\.{re.escape(mark)}\n", "", result)

    # Replace bare symbols with utils. prefix
    for sym in UTILS_SYMBOLS:
        # Only replace bare occurrences (not already prefixed)
        result = re.sub(rf"(?<!\.)(?<!\w){re.escape(sym)}\b", f"utils.{sym}", result)

    # Replace device reference
    result = result.replace("device=device", "device=flag_gems.device")


    return result


def generate_max_pool2d_with_indices_backward_test():
    return 'import pytest\nimport torch\n\nimport flag_gems\n\nfrom . import accuracy_utils as utils\n\n# Core cases cover common max-pool backward parameter combinations.\nMAX_POOL2D_WITH_INDICES_BACKWARD_CONFIGS = [\n    ((4, 3, 32, 32), 3, 2, 1, 1, False),\n    ((8, 16, 28, 28), (3, 5), (1, 2), 1, 1, False),\n    ((2, 4, 15, 15), 3, 2, 1, 1, True),\n    ((1, 1, 7, 7), 2, 1, 0, 2, False),\n    ((1, 64, 56, 56), 3, 2, 1, 1, False),\n    ((2, 8, 16, 16), 2, 2, 0, 1, False),\n    ((2, 8, 16, 20), 2, 2, (1, 0), 1, False),\n]\n\n\ndef _pair(value):\n    if isinstance(value, int):\n        return (value, value)\n    return tuple(value)\n\n\ndef _stride_pair(stride, kernel_size):\n    return _pair(kernel_size if stride is None else stride)\n\n\n@pytest.mark.max_pool2d_with_indices_backward\n@pytest.mark.parametrize(\n    "shape, kernel_size, stride, padding, dilation, ceil_mode",\n    MAX_POOL2D_WITH_INDICES_BACKWARD_CONFIGS,\n)\n@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)\ndef test_max_pool2d_with_indices_backward(\n    shape, kernel_size, stride, padding, dilation, ceil_mode, dtype\n):\n    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device, requires_grad=True)\n    ref_inp = utils.to_reference(inp, upcast=True)\n\n    ref_out, _ = torch.nn.functional.max_pool2d_with_indices(\n        ref_inp,\n        kernel_size=kernel_size,\n        stride=stride,\n        padding=padding,\n        dilation=dilation,\n        ceil_mode=ceil_mode,\n    )\n    with flag_gems.use_gems():\n        res_out, res_indices = torch.nn.functional.max_pool2d_with_indices(\n            inp,\n            kernel_size=kernel_size,\n            stride=stride,\n            padding=padding,\n            dilation=dilation,\n            ceil_mode=ceil_mode,\n        )\n\n    out_grad = torch.randn_like(res_out, device=flag_gems.device)\n    ref_grad = utils.to_reference(out_grad, upcast=True)\n    (ref_in_grad,) = torch.autograd.grad(ref_out, ref_inp, ref_grad)\n\n    with flag_gems.use_gems():\n        res_in_grad = torch.ops.aten.max_pool2d_with_indices_backward(\n            out_grad,\n            inp,\n            _pair(kernel_size),\n            _stride_pair(stride, kernel_size),\n            _pair(padding),\n            _pair(dilation),\n            ceil_mode,\n            res_indices,\n        )\n\n    utils.gems_assert_close(res_in_grad, ref_in_grad, dtype)\n'


def generate_max_pool2d_with_indices_backward_benchmark():
    return 'from typing import Generator\n\nimport pytest\nimport torch\n\nimport flag_gems\n\nfrom . import base, consts, utils\n\n\ndef _pair(value):\n    if isinstance(value, int):\n        return (value, value)\n    return tuple(value)\n\n\ndef _stride_pair(stride, kernel_size):\n    return _pair(kernel_size if stride is None else stride)\n\n\ndef _aten_params(kwargs):\n    return (\n        _pair(kwargs["kernel_size"]),\n        _stride_pair(kwargs["stride"], kwargs["kernel_size"]),\n        _pair(kwargs["padding"]),\n        _pair(kwargs["dilation"]),\n        kwargs["ceil_mode"],\n    )\n\n\nclass MaxPool2dWithIndicesBackwardBenchmark(base.GenericBenchmark):\n    def set_shapes(self, shape_file_path=None):\n        # Common CNN feature-map sizes keep the core backward benchmark compact.\n        self.shapes = [\n            (4, 3, 224, 224),\n            (16, 64, 56, 56),\n            (32, 128, 28, 28),\n            (64, 256, 14, 14),\n            (128, 512, 7, 7),\n        ]\n\n    def get_input_iter(self, dtype) -> Generator:\n        for shape in self.shapes:\n            yield from self.input_fn(shape, dtype, self.device)\n\n\ndef max_pool2d_with_indices_backward_input_fn(shape, dtype, device):\n    inp = utils.generate_tensor_input(shape, dtype, device)\n    params = {\n        "kernel_size": 3,\n        "stride": 2,\n        "padding": 1,\n        "dilation": 1,\n        "ceil_mode": False,\n    }\n\n    _, torch_indices = torch.nn.functional.max_pool2d_with_indices(inp, **params)\n    with flag_gems.use_gems():\n        output, gems_indices = torch.nn.functional.max_pool2d_with_indices(\n            inp, **params\n        )\n    grad_output = torch.randn_like(output)\n    yield grad_output, inp, torch_indices, gems_indices, params\n\n\ndef torch_max_pool2d_with_indices_backward_wrapper(\n    grad_output, input, torch_indices, gems_indices, **kwargs\n):\n    kernel_size, stride, padding, dilation, ceil_mode = _aten_params(kwargs)\n    return torch.ops.aten.max_pool2d_with_indices_backward(\n        grad_output,\n        input,\n        kernel_size,\n        stride,\n        padding,\n        dilation,\n        ceil_mode,\n        torch_indices,\n    )\n\n\ndef flag_gems_max_pool2d_with_indices_backward_wrapper(\n    grad_output, input, torch_indices, gems_indices, **kwargs\n):\n    kernel_size, stride, padding, dilation, ceil_mode = _aten_params(kwargs)\n    with flag_gems.use_gems():\n        return torch.ops.aten.max_pool2d_with_indices_backward(\n            grad_output,\n            input,\n            kernel_size,\n            stride,\n            padding,\n            dilation,\n            ceil_mode,\n            gems_indices,\n        )\n\n\n@pytest.mark.max_pool2d_with_indices_backward\ndef test_max_pool2d_with_indices_backward():\n    bench = MaxPool2dWithIndicesBackwardBenchmark(\n        input_fn=max_pool2d_with_indices_backward_input_fn,\n        op_name="max_pool2d_with_indices_backward",\n        torch_op=torch_max_pool2d_with_indices_backward_wrapper,\n        dtypes=consts.FLOAT_DTYPES,\n    )\n    bench.set_gems(flag_gems_max_pool2d_with_indices_backward_wrapper)\n    bench.run()\n'


def extract_test(op, worktree, repo, dry_run):
    section("Step 2: Test 文件")
    op_id = get_op_id(op)
    dst = os.path.join(repo, f"tests/test_{op_id}.py")

    if is_max_pool2d_with_indices_backward(op):
        test_content = generate_max_pool2d_with_indices_backward_test()
        if dry_run:
            ok(f"[DRY] 将写入 {dst}")
            print(f"    预览:\n{test_content[:500]}")
        else:
            with open(dst, "w") as f:
                f.write(test_content)
            ok(f"已生成: {dst}")
        return

    fpath, content, func_name = find_test_function(op, worktree)
    if not fpath:
        fatal(f"worktree 中未找到 test_accuracy_{op_id} 或 test_{op_id} 函数")

    ok(f"找到测试: {os.path.basename(fpath)}:{func_name}")

    # Find all related test functions (including variants like _list_padding, _empty_padding)
    all_funcs = find_all_related_test_functions(content, op_id, func_name)
    ok(f"找到 {len(all_funcs)} 个相关测试函数: {', '.join(all_funcs)}")

    blocks = []
    for fn in all_funcs:
        block = extract_function_block(content, fn)
        if block:
            block = convert_test_imports(block, op)
            blocks.append(block)

    if not blocks:
        fatal(f"无法提取函数 {func_name}")

    combined_blocks = "\n\n\n".join(blocks)

    extra_imports = ""
    if re.search(r"\brandom\.", combined_blocks):
        extra_imports += "import random\n"
    if re.search(r"\bmath\.", combined_blocks):
        extra_imports += "import math\n"

    test_content = (
        f"{extra_imports}"
        "import pytest\n"
        "import torch\n"
        "\n"
        "import flag_gems\n"
        "\n"
        "from . import accuracy_utils as utils\n"
        "\n"
        "\n"
        f"{combined_blocks}\n"
    )

    if dry_run:
        ok(f"[DRY] 将写入 {dst}")
        print(f"    预览:\n{test_content[:500]}")
    else:
        with open(dst, "w") as f:
            f.write(test_content)
        ok(f"已生成: {dst}")


# ---------------------------------------------------------------------------
# Step 3: Benchmark file
# ---------------------------------------------------------------------------


def find_benchmark_code(op, worktree):
    """Find benchmark code for the operator in worktree."""
    op_id = get_op_id(op)
    bench_dir = os.path.join(worktree, "benchmark")

    for fname in os.listdir(bench_dir):
        if not fname.endswith(".py"):
            continue
        fpath = os.path.join(bench_dir, fname)
        with open(fpath) as f:
            content = f.read()
        if (f"mark.{op_id}" in content or f'op_name="{op_id}"' in content
                or f'"{op_id}"' in content
                or f'op_name="{op}"' in content or f'mark.{op_id.rstrip("_")}' in content):
            return fpath, content

    return None, None


def extract_benchmark_block(content, op, source_file):
    """Extract benchmark related code (class, input_fn, test function)."""
    op_id = get_op_id(op)
    lines = content.split("\n")
    blocks = []

    # Strategy 1: Find standalone class + test function (e.g., RandintBenchmark)
    class_pattern = re.compile(rf"class \w*{re.escape(op_id)}\w*Benchmark", re.IGNORECASE)
    for i, line in enumerate(lines):
        if class_pattern.search(line):
            cls_name = line.split("class ")[1].split("(")[0].split(":")[0]
            block = extract_function_block(content, cls_name)
            if block:
                blocks.append(("class", block))

    # Strategy 2: Find input_fn for this op
    input_fn_names = [
        f"{op_id}_input_fn", f"_{op_id}_input_fn", f"_input_fn",
    ]
    for fn_name in input_fn_names:
        for i, line in enumerate(lines):
            if f"def {fn_name}" in line:
                block = extract_function_block(content, fn_name)
                if block:
                    blocks.append(("input_fn", block))
                break

    # Strategy 3: Find standalone test function (e.g., test_perf_randint)
    test_patterns = [
        rf"def test_(?:perf_)?{re.escape(op_id)}\b",
        rf"def test_{re.escape(op_id)}\b",
        rf"def test_{re.escape(op)}\b",
        rf"def test_{re.escape(op)}_perf\b",
    ]
    for pat in test_patterns:
        for i, line in enumerate(lines):
            if re.search(pat, line):
                fname = re.search(r"def (\w+)", line).group(1)
                block = extract_function_block(content, fname)
                if block:
                    blocks.append(("test", block))
                break
        if any(t == "test" for t, _ in blocks):
            break

    # Strategy 4: op in a parametrized list → generate standalone benchmark
    if not any(t == "test" for t, _ in blocks):
        list_entry = _find_list_entry(lines, op_id, source_file)
        if list_entry:
            blocks.append(("list_entry", list_entry))

    test_text = "\n".join(b for t, b in blocks if t == "test" and isinstance(b, str))
    if test_text:
        existing_classes = {
            re.search(r"class\s+(\w+)", b).group(1)
            for t, b in blocks
            if t == "class" and isinstance(b, str) and re.search(r"class\s+(\w+)", b)
        }
        for cls_name in sorted(set(re.findall(r"\b([A-Z]\w*Benchmark)\s*\(", test_text))):
            if cls_name in existing_classes:
                continue
            block = extract_function_block(content, cls_name)
            if block and not block.splitlines()[0].startswith((" ", "\t")):
                blocks.insert(0, ("class", block))
                existing_classes.add(cls_name)

        existing_funcs = {
            re.search(r"def\s+(\w+)", b).group(1)
            for t, b in blocks
            if t == "input_fn" and isinstance(b, str) and re.search(r"def\s+(\w+)", b)
        }
        for fn_name in sorted(set(re.findall(r"\b(\w+_input_fn)\s*\(", test_text))):
            if fn_name in existing_funcs:
                continue
            block = extract_function_block(content, fn_name)
            if block and not block.splitlines()[0].startswith((" ", "\t")):
                insert_idx = 1 if blocks and blocks[0][0] == "class" else 0
                blocks.insert(insert_idx, ("input_fn", block))
                existing_funcs.add(fn_name)

    return blocks


def _find_list_entry(lines, op_id, source_file):
    """Find op in a parametrized operations list and return benchmark info dict."""
    basename = os.path.basename(source_file) if source_file else ""

    for i, line in enumerate(lines):
        stripped = line.strip()
        if f'"{op_id}"' not in stripped:
            continue

        tuple_text = _collect_tuple_text(lines, i)
        parsed = _parse_tuple_entry(tuple_text, op_id, basename) if tuple_text else None
        if parsed:
            parsed["is_inplace"] = _infer_is_inplace_context(lines, i)
            parsed["comments"] = _collect_preceding_comments(lines, i)
            return parsed

        # Parse single-line entries:
        #   ("op_name", torch.op, [dtypes])
        #   ("op_name", lambda a, b: a.__and__(b), INT_DTYPES + BOOL_DTYPES)
        prefix_match = re.match(rf'\(\s*"{re.escape(op_id)}"\s*,\s*(.+?)\s*\),?\s*$', stripped)
        if not prefix_match:
            continue

        args_part = prefix_match.group(1)
        if "," in args_part:
            torch_op, third_arg = [part.strip().rstrip(",") for part in args_part.rsplit(",", 1)]
        else:
            torch_op, third_arg = args_part.strip(), None

        # Determine benchmark type from file name
        bench_type = _classify_bench_type(basename)

        # Determine dtypes
        dtypes = _resolve_dtypes(third_arg)

        return {
            "type": bench_type,
            "torch_op": torch_op,
            "dtypes": dtypes,
            "op_id": op_id,
            "is_inplace": _infer_is_inplace_context(lines, i),
            "comments": _collect_preceding_comments(lines, i),
        }

    # Fallback: handle multi-line tuples where "op_name" and "torch.op" are on different lines
    for i, line in enumerate(lines):
        stripped = line.strip()
        if f'"{op_id}"' not in stripped:
            continue

        # Look for the enclosing tuple: join from "(" to matching ")"
        start = i
        while start >= 0 and "(" not in lines[start]:
            start -= 1
        end = i
        while end < len(lines) and ")" not in lines[end]:
            end += 1

        if start < 0 or end >= len(lines):
            continue

        joined = " ".join(lines[start:end + 1])
        # Now try to match the joined multi-line tuple
        match = re.search(
            rf'\(\s*"{re.escape(op_id)}"\s*,\s*([\w.\s,]+?)\s*\)',
            joined
        )
        if not match:
            continue

        args_part = match.group(1).strip().rstrip(",")
        # Split into parts: torch_op and optional dtypes/input_fn
        parts = [p.strip().rstrip(",") for p in args_part.split(",")]
        torch_op = None
        dtypes = None

        for p in parts:
            if re.match(r'^[\w.]+$', p) and "torch" in p:
                torch_op = p
            elif p.startswith("[") or re.match(r'^[A-Z_]+$', p):
                dtypes = _resolve_dtypes(p)
                break  # last meaningful arg after torch_op

        if not torch_op:
            continue

        bench_type = _classify_bench_type(basename)

        return {
            "type": bench_type,
            "torch_op": torch_op,
            "dtypes": dtypes,
            "op_id": op_id,
            "is_inplace": _infer_is_inplace_context(lines, i),
            "comments": _collect_preceding_comments(lines, i),
        }

    return None


def _collect_tuple_text(lines, entry_line):
    """Collect the complete tuple text for an op list entry."""
    start = entry_line
    while start >= 0 and not lines[start].lstrip().startswith("("):
        start -= 1
    if start < 0:
        return None

    collected = []
    depth = 0
    seen_open = False
    for j in range(start, len(lines)):
        part = lines[j].split("#", 1)[0]
        collected.append(lines[j].strip())
        depth += part.count("(") - part.count(")")
        seen_open = seen_open or "(" in part
        if seen_open and depth <= 0:
            break

    if not collected:
        return None
    return " ".join(collected).strip()


def _parse_tuple_entry(tuple_text, op_id, source_file):
    """Parse a parametrized benchmark tuple without splitting lambda commas."""
    expr = tuple_text.strip().rstrip(",")
    try:
        parsed = ast.parse(expr, mode="eval")
    except SyntaxError:
        return None

    node = parsed.body
    if not isinstance(node, ast.Tuple) or len(node.elts) < 2:
        return None
    name_node = node.elts[0]
    if not isinstance(name_node, ast.Constant) or name_node.value != op_id:
        return None

    torch_op = ast.get_source_segment(expr, node.elts[1]) or ast.unparse(node.elts[1])
    dtypes = None
    if len(node.elts) >= 3:
        dtypes = ast.get_source_segment(expr, node.elts[2]) or ast.unparse(node.elts[2])

    return {
        "type": _classify_bench_type(source_file),
        "torch_op": torch_op,
        "dtypes": _resolve_dtypes(dtypes),
        "op_id": op_id,
    }


def _infer_is_inplace_context(lines, entry_line):
    """Infer whether a parametrized entry belongs to an inplace benchmark."""
    for line in lines[entry_line: min(len(lines), entry_line + 100)]:
        stripped = line.strip()
        if stripped.startswith("@pytest.mark.parametrize") and line != lines[entry_line]:
            break
        if "is_inplace=True" in stripped:
            return True
    return False


def _collect_preceding_comments(lines, entry_line):
    comments = []
    j = entry_line - 1
    while j >= 0:
        stripped = lines[j].strip()
        if stripped.startswith("#"):
            comments.insert(0, stripped)
            j -= 1
            continue
        if stripped == "" and comments:
            j -= 1
            continue
        break
    return comments


def _classify_bench_type(basename):
    if "unary_pointwise" in basename:
        return "unary"
    elif "binary_pointwise" in basename:
        return "binary"
    return "generic"


def _resolve_dtypes(third_arg):
    if third_arg and third_arg.startswith("["):
        return third_arg
    if third_arg and "_DTYPES" in third_arg:
        return third_arg
    return None


def _prefix_consts_dtypes(expr):
    """Prefix bare benchmark dtype constants with consts."""
    return re.sub(r"(?<!consts\.)(?<!\w)([A-Z_]+_DTYPES)\b", r"consts.\1", expr)


def _format_torch_op_kwarg(torch_op):
    line = f"        torch_op={torch_op},\n"
    if len(line.rstrip("\n")) <= 120:
        return line

    if (
        torch_op.startswith("lambda a, b: torch.float_power(")
        and ").to(a.dtype)" in torch_op
    ):
        return (
            "        torch_op=(\n"
            "            lambda a, b: torch.float_power(\n"
            "                a.to(torch.float64), b.to(torch.float64)\n"
            "            ).to(a.dtype)\n"
            "        ),\n"
        )

    return line


def generate_benchmark_file(blocks, op, bench_source_file):
    """Generate independent benchmark file from extracted blocks."""
    op_id = get_op_id(op)

    has_class = any(t == "class" for t, _ in blocks)
    has_test = any(t == "test" for t, _ in blocks)
    list_entry = next((b for t, b in blocks if t == "list_entry"), None)

    # Case A: standalone class + input_fn + test function → combine them
    if has_class or has_test:
        if has_test:
            blocks = [
                (btype, block)
                for btype, block in blocks
                if not (
                    btype == "input_fn"
                    and isinstance(block, str)
                    and block.splitlines()
                    and block.splitlines()[0].startswith((" ", "\t"))
                )
            ]
        all_block_text = "\n".join(b for _, b in blocks if isinstance(b, str))
        needs_consts = ("consts." in all_block_text or "FLOAT_DTYPES" in all_block_text
                        or "INT_DTYPES" in all_block_text)
        needs_torch = "torch." in all_block_text
        needs_flag_gems = "flag_gems" in all_block_text

        header = "import pytest\n"
        if needs_torch:
            header += "import torch\n"
        if needs_flag_gems:
            header += "\nimport flag_gems\n"
        header += "\nfrom . import base"
        if needs_consts:
            header += ", consts"
        header += "\n"

        parts = [header]
        for btype, block in blocks:
            if not isinstance(block, str):
                continue
            if btype == "test":
                block = re.sub(rf"def test_perf_{re.escape(op_id)}\b",
                               f"def test_{op_id}", block)
            parts.append(f"\n\n{block}")

        content = "\n".join(parts)

        # Add base. prefix to benchmark classes if not already prefixed
        for cls in ["GenericBenchmark", "GenericBenchmarkExcluse1D",
                     "GenericBenchmarkExcluse3D", "GenericBenchmark2DOnly",
                     "GenericBenchmark4DOnly", "UnaryPointwiseBenchmark",
                     "BinaryPointwiseBenchmark", "UnaryReductionBenchmark",
                     "BlasBenchmark", "Benchmark"]:
            content = re.sub(rf"(?<!base\.)(?<!\w){cls}\(", f"base.{cls}(", content)
            content = re.sub(rf"(?<!base\.)(?<!\w){cls}\)", f"base.{cls})", content)
        content = content.replace("base.base.", "base.")

        # Add consts. prefix
        for const in ["FLOAT_DTYPES", "INT_DTYPES", "EXTRA_INT_DTYPES"]:
            content = re.sub(rf"(?<!consts\.)(?<!\w){const}\b", f"consts.{const}", content)
        content = content.replace("consts.consts.", "consts.")
        content = re.sub(r"(?<!base\.)(?<!\w)vendor_name\b", "base.vendor_name", content)
        content = re.sub(r"(?<!base\.)(?<!\w)Config\b", "base.Config", content)
        content = re.sub(r"(?<!consts\.)(?<!\w)BenchLevel\b", "consts.BenchLevel", content)
        content = content.replace(
            "        dtypes=[torch.float32] if base.vendor_name == \"mthreads\" else consts.FLOAT_DTYPES,\n",
            "        # MThreads supports only float32 here; NVIDIA uses consts.FLOAT_DTYPES.\n"
            "        dtypes=[torch.float32] if base.vendor_name == \"mthreads\" else consts.FLOAT_DTYPES,\n",
        )

    # Case B: list entry → generate standard benchmark
    elif list_entry:
        info = list_entry
        torch_op = info["torch_op"]
        dtypes_str = info.get("dtypes")

        if info["type"] == "unary":
            cls = "base.UnaryPointwiseBenchmark"
        elif info["type"] == "binary":
            cls = "base.BinaryPointwiseBenchmark"
        else:
            cls = "base.GenericBenchmark"

        # Build dtypes argument
        if dtypes_str:
            # Bare DTYPES names need consts. prefix
            if re.match(r'^[A-Z_]+_DTYPES$', dtypes_str):
                dtypes_arg = f"dtypes=consts.{dtypes_str}"
                needs_consts = True
            elif dtypes_str.startswith("["):
                dtypes_arg = f"dtypes={dtypes_str}"
                needs_consts = False
            else:
                dtypes_expr = _prefix_consts_dtypes(dtypes_str)
                dtypes_arg = f"dtypes={dtypes_expr}"
                needs_consts = "consts." in dtypes_expr
        else:
            dtypes_arg = "dtypes=consts.FLOAT_DTYPES"
            needs_consts = True

        needs_torch = "torch." in torch_op
        header = "import pytest\n"
        if needs_torch:
            header += "import torch\n"
        header += "\nfrom . import base"
        if needs_consts:
            header += ", consts"
        header += "\n"

        content = f"""{header}


@pytest.mark.{op_id}
def test_{op_id}():
    bench = {cls}(
        op_name="{op_id}",
"""
        content += _format_torch_op_kwarg(torch_op)
        for comment in info.get("comments", []):
            content += f"        {comment}\n"
        content += f"        {dtypes_arg},\n"
        if info.get("is_inplace"):
            content += "        is_inplace=True,\n"
        content += """    )
    bench.run()
"""
    else:
        return None

    if not content.endswith("\n"):
        content += "\n"
    return content


def extract_benchmark(op, worktree, repo, dry_run):
    section("Step 3: Benchmark 文件")
    op_id = get_op_id(op)
    dst = os.path.join(repo, f"benchmark/test_{op_id}.py")

    if is_max_pool2d_with_indices_backward(op):
        bench_content = generate_max_pool2d_with_indices_backward_benchmark()
        if dry_run:
            ok(f"[DRY] 将写入 {dst}")
            print(f"    预览:\n{bench_content[:500]}")
        else:
            with open(dst, "w") as f:
                f.write(bench_content)
            ok(f"已生成: {dst}")
        return

    fpath, content = find_benchmark_code(op, worktree)
    if not fpath:
        fatal(f"worktree benchmark 中未找到 {op_id} 相关代码")

    ok(f"找到 benchmark: {os.path.basename(fpath)}")

    blocks = extract_benchmark_block(content, op, fpath)
    if not blocks:
        fatal(f"无法提取 benchmark 代码块")

    ok(f"提取到 {len(blocks)} 个代码块: {[t for t, _ in blocks]}")

    bench_content = generate_benchmark_file(blocks, op, fpath)

    if not bench_content:
        fatal("无法生成 benchmark 文件内容")

    if dry_run:
        ok(f"[DRY] 将写入 {dst}")
        print(f"    预览:\n{bench_content[:500]}")
    else:
        with open(dst, "w") as f:
            f.write(bench_content)
        ok(f"已生成: {dst}")


# ---------------------------------------------------------------------------
# Step 4: ops/__init__.py
# ---------------------------------------------------------------------------


def insert_existing_ops_init_name(repo_init, module_name, name, dry_run):
    with open(repo_init) as f:
        repo_lines = f.read().split("\n")

    import_start = None
    import_end = None
    import_prefix = f"from flag_gems.ops.{module_name} import"
    for i, line in enumerate(repo_lines):
        if line.startswith(import_prefix):
            import_start = i
            if line.rstrip().endswith("("):
                for j in range(i + 1, len(repo_lines)):
                    if repo_lines[j].strip() == ")":
                        import_end = j
                        break
            else:
                import_end = i
            break

    if import_start is None:
        fatal(f"未找到 import: {import_prefix}")

    if import_start == import_end:
        current = repo_lines[import_start].split(" import ", 1)[1]
        names = [n.strip() for n in current.split(",") if n.strip()]
        if name not in names:
            names.append(name)
            names = sorted(names)
            repo_lines[import_start] = f"{import_prefix} {', '.join(names)}"
            ok(f"import 添加 {name}")
        else:
            ok(f"import 已包含 {name}")
    else:
        names = []
        for i in range(import_start + 1, import_end):
            stripped = repo_lines[i].strip().rstrip(",")
            if stripped:
                names.append(stripped)
        if name not in names:
            names.append(name)
            names = sorted(names)
            repo_lines[import_start + 1:import_end] = [f"    {n}," for n in names]
            ok(f"import 添加 {name}")
        else:
            ok(f"import 已包含 {name}")

    all_start = None
    all_end = None
    for i, line in enumerate(repo_lines):
        if "__all__" in line and "=" in line:
            all_start = i
        if all_start is not None and line.strip() == "]":
            all_end = i
            break
    if all_start is None or all_end is None:
        fatal("未找到 __all__ 定义")

    all_entries = []
    for i in range(all_start, all_end + 1):
        all_entries.extend(re.findall(r'"(\w+)"', repo_lines[i]))
    if name not in all_entries:
        insert_idx = all_end
        for i in range(all_start + 1, all_end):
            match = re.search(r'"(\w+)"', repo_lines[i])
            if match and name < match.group(1):
                insert_idx = i
                break
        repo_lines.insert(insert_idx, f'    "{name}",')
        ok(f'__all__ 添加 "{name}"')
    else:
        ok(f'__all__ 已包含 "{name}"')

    if dry_run:
        ok("[DRY] ops/__init__.py 将被更新")
    else:
        with open(repo_init, "w") as f:
            f.write("\n".join(repo_lines))
        ok("ops/__init__.py 已更新")


def insert_ops_init(op, worktree, repo, dry_run):
    section("Step 4: ops/__init__.py")
    module_name = get_module_name(op)
    wt_init = os.path.join(worktree, "src/flag_gems/ops/__init__.py")
    repo_init = os.path.join(repo, "src/flag_gems/ops/__init__.py")

    if is_max_pool2d_with_indices_backward(op):
        insert_existing_ops_init_name(
            repo_init, module_name, "max_pool2d_with_indices_backward", dry_run
        )
        return

    # Extract import line and __all__ entries from worktree
    with open(wt_init) as f:
        wt_content = f.read()

    import_pattern = rf"^from flag_gems\.ops\.{re.escape(module_name)} import\b"
    import_line = None
    import_block = None
    wt_lines = wt_content.split("\n")
    for i, line in enumerate(wt_lines):
        if re.match(import_pattern, line):
            import_line = line
            # Check if multi-line import (ends with open paren)
            if line.rstrip().endswith("("):
                # Collect until closing paren
                block_lines = [line]
                for j in range(i + 1, len(wt_lines)):
                    block_lines.append(wt_lines[j])
                    if ")" in wt_lines[j]:
                        break
                import_block = "\n".join(block_lines)
            else:
                import_block = line
            break

    if not import_line:
        fatal(f"worktree ops/__init__.py 中未找到 {op} 的 import")

    # Extract __all__ names for this op (from the full block)
    all_names_match = re.search(
        rf'from flag_gems\.ops\.{re.escape(module_name)} import (.+)',
        import_block,
        re.DOTALL,
    )
    if all_names_match:
        all_names_raw = all_names_match.group(1)
        # Remove parens, strip whitespace
        all_names_raw = all_names_raw.replace("(", "").replace(")", "").replace("\n", " ")
        names = [n.strip().rstrip(",") for n in all_names_raw.split(",") if n.strip()]
    else:
        fatal(f"无法从 import 块提取导出名")
    ok(f"import 块: {import_block}")
    ok(f"导出名: {names}")

    # Read repo file
    with open(repo_init) as f:
        repo_content = f.read()

    # Insert import line in alphabetical order
    repo_lines = repo_content.split("\n")
    import_section_end = 0
    existing_imports = []
    for i, line in enumerate(repo_lines):
        if line.startswith("from flag_gems.ops."):
            existing_imports.append((i, line))
            import_section_end = i

    # Check if already exists
    if any(import_line in line for _, line in existing_imports):
        ok("import 已存在，跳过")
        all_end_adjust = 0
    else:
        # Find insertion point by alphabetical order
        insert_idx = import_section_end + 1
        for i, line in existing_imports:
            match = re.match(r"from flag_gems\.ops\.(\w+) import", line)
            if match:
                existing_mod = match.group(1)
                sort_key_existing = (not existing_mod.startswith("_"), existing_mod)
                sort_key_new = (not module_name.startswith("_"), module_name)
                if sort_key_new < sort_key_existing:
                    insert_idx = i
                    break
                insert_idx = i + 1

        # Insert multi-line import block (each line separately)
        block_lines = import_block.split("\n")
        for j, bline in enumerate(block_lines):
            repo_lines.insert(insert_idx + j, bline)
        ok(f"import 插入位置: 行 {insert_idx + 1} ({len(block_lines)} 行)")
        all_end_adjust = len(block_lines)  # __all__ end shifts by this much

    # Track how many lines were added for __all__ calculation

    # Insert into __all__
    # Find __all__ block
    all_start = None
    all_end = None
    for i, line in enumerate(repo_lines):
        if "__all__" in line and "=" in line:
            all_start = i
        if all_start and line.strip() == "]":
            all_end = i
            break

    if all_start and all_end:
        # Extract current __all__ entries
        all_entries = []
        for i in range(all_start, all_end + 1):
            matches = re.findall(r'"(\w+)"', repo_lines[i])
            all_entries.extend(matches)

        for name in names:
            if name in all_entries:
                ok(f'__all__ 已包含 "{name}"')
                continue

            # Find insertion point
            insert_idx = all_end
            for i in range(all_start + 1, all_end):
                match = re.search(r'"(\w+)"', repo_lines[i])
                if match:
                    existing = match.group(1)
                    if name < existing:
                        insert_idx = i
                        break
                    insert_idx = i + 1

            entry = f'    "{name}",'
            repo_lines.insert(insert_idx, entry)
            all_end += 1
            ok(f'__all__ 插入 "{name}" 在行 {insert_idx + 1}')

    new_content = "\n".join(repo_lines)

    if dry_run:
        ok("[DRY] ops/__init__.py 将被更新")
    else:
        with open(repo_init, "w") as f:
            f.write(new_content)
        ok("ops/__init__.py 已更新")


# ---------------------------------------------------------------------------
# Step 5: _FULL_CONFIG
# ---------------------------------------------------------------------------


def insert_full_config(op, worktree, repo, dry_run):
    section("Step 5: _FULL_CONFIG")
    wt_init = os.path.join(worktree, "src/flag_gems/__init__.py")
    repo_init = os.path.join(repo, "src/flag_gems/__init__.py")

    # Extract config entries from worktree
    with open(wt_init) as f:
        wt_content = f.read()

    # Find all config entries for this op
    op_id = get_op_id(op)
    naming = resolve_op(op)
    config_entries = []
    if naming.config_entries:
        config_entries = [
            f'("{aten_name}", {func_name}),' for aten_name, func_name in naming.config_entries
        ]
    else:
        for line in wt_content.split("\n"):
            line_stripped = line.strip()
            if line_stripped.startswith("(") and ("," in line_stripped):
                match = re.match(r'\(\s*"([^"]+)"\s*,\s*(\w+)', line_stripped)
                if match:
                    aten_name, func_name = match.groups()
                    base_name = aten_name.split(".")[0].lstrip("_")
                    if base_name == op or base_name == op_id or func_name == op or func_name == op_id:
                        config_entries.append(line_stripped.rstrip(",") + ",")

    if not config_entries:
        fatal(f"worktree _FULL_CONFIG 中未找到 {op} 的条目")

    for entry in config_entries:
        ok(f"配置: {entry}")

    # Read repo file
    with open(repo_init) as f:
        repo_content = f.read()

    repo_lines = repo_content.split("\n")

    # Find _FULL_CONFIG block
    config_start = None
    config_end = None
    for i, line in enumerate(repo_lines):
        if "_FULL_CONFIG" in line and "=" in line:
            config_start = i
        if config_start and line.strip() == ")":
            config_end = i
            break

    if not config_start or not config_end:
        fatal("未找到 _FULL_CONFIG 定义")

    # Insert each entry
    indent = "    "
    for entry in config_entries:
        match = re.match(r'\(\s*"([^"]+)"', entry)
        if not match:
            continue
        aten_name = match.group(1)

        # Check if already exists
        if f'"{aten_name}"' in repo_content:
            desired_entry = f'{indent}{entry}'
            for idx, line in enumerate(repo_lines):
                if f'"{aten_name}"' in line:
                    if line != desired_entry:
                        repo_lines[idx] = desired_entry
                        ok(f'_FULL_CONFIG 更新 "{aten_name}" 目标函数')
                    else:
                        ok(f'_FULL_CONFIG 已包含 "{aten_name}"')
                    break
            continue

        # Find insertion point by alphabetical order of aten name
        insert_idx = config_end
        for i in range(config_start + 1, config_end):
            line_match = re.search(r'\(\s*"([^"]+)"', repo_lines[i])
            if line_match:
                existing_name = line_match.group(1)
                if aten_name < existing_name:
                    insert_idx = i
                    break
                insert_idx = i + 1

        indent = "    "
        repo_lines.insert(insert_idx, f"{indent}{entry}")
        config_end += 1
        ok(f'_FULL_CONFIG 插入 "{aten_name}" 在行 {insert_idx + 1}')

    new_content = "\n".join(repo_lines)

    if dry_run:
        ok("[DRY] __init__.py 将被更新")
    else:
        with open(repo_init, "w") as f:
            f.write(new_content)
        ok("__init__.py 已更新")


# ---------------------------------------------------------------------------
# Step 6: operators.yaml
# ---------------------------------------------------------------------------


def insert_operators_yaml(op, worktree, repo, dry_run):
    section("Step 6: operators.yaml")
    op_id = get_op_id(op)
    repo_yaml = os.path.join(repo, "conf/operators.yaml")
    wt_yaml = os.path.join(worktree, "conf/operators.yaml")

    with open(repo_yaml) as f:
        repo_data = yaml.safe_load(f)

    # Check if already exists
    existing_ids = [o.get("id") for o in repo_data.get("ops", [])]
    if op_id in existing_ids:
        ok(f"operators.yaml 已包含 id: {op_id}")
        # Still check inplace split below
    else:
        # Try to get entry from worktree yaml
        entry = None
        with open(wt_yaml) as f:
            wt_data = yaml.safe_load(f)
        for wt_op in wt_data.get("ops", []):
            wt_name = wt_op.get("name", wt_op.get("id", ""))
            if wt_name == op or wt_name == op_id:
                entry = dict(wt_op)
                if "name" in entry:
                    entry["id"] = op_id
                    del entry["name"]
                break

        if not entry:
            naming = resolve_op(op)
            entry = {
                "id": op_id,
                "description": naming.yaml_description or f"Triton kernel implementation for {op}.\n",
                "for": list(naming.yaml_for or (op,)),
                "labels": ["aten", "KernelGen"],
                "kind": ["Math"],
                "stages": [{"alpha": "5.4"}],
            }
            if is_max_pool2d_with_indices_backward(op):
                entry["kind"] = ["NeuralNetwork"]
            warn(f"worktree yaml 无此算子，使用默认条目（description 需人工补充）")
        else:
            labels = entry.get("labels", [])
            if "KernelGen" not in labels:
                labels.append("KernelGen")
                entry["labels"] = labels
            entry["id"] = op_id
            stages = entry.get("stages", {})
            if isinstance(stages, dict):
                entry["stages"] = [{k: v} for k, v in stages.items()]
            ok(f"从 worktree yaml 提取条目")

        # Split: if entry's 'for' list contains both op and op_ (inplace), split them
        for_list = entry.get("for", [])
        inplace_items = [f for f in for_list if f.rstrip(".").endswith("_") and f.rstrip("_.") == op.rstrip("_")]
        non_inplace_items = [f for f in for_list if f not in inplace_items]

        if inplace_items and non_inplace_items:
            warn(f"检测到 for 列表同时包含 inplace 和非 inplace: {for_list}，自动拆分")
            entry["for"] = non_inplace_items
            _insert_yaml_entry(entry, repo_yaml, op_id, existing_ids, dry_run)
            # Create separate inplace entry
            inplace_entry = dict(entry)
            inplace_id = op_id + "_"
            inplace_entry["id"] = inplace_id
            inplace_entry["description"] = f"The in-place version of `{op_id}()`."
            inplace_entry["for"] = inplace_items
            if inplace_id not in existing_ids:
                _insert_yaml_entry(inplace_entry, repo_yaml, inplace_id, existing_ids, dry_run)
                ok(f"已拆分 inplace 变体为独立条目: id={inplace_id}")
        else:
            _insert_yaml_entry(entry, repo_yaml, op_id, existing_ids, dry_run)

    # Check _FULL_CONFIG for inplace variant not in yaml
    wt_init = os.path.join(worktree, "src/flag_gems/__init__.py")
    if os.path.isfile(wt_init):
        with open(wt_init) as f:
            wt_content = f.read()
        inplace_op = op + "_" if not op.endswith("_") else None
        if inplace_op:
            inplace_id = get_op_id(inplace_op)
            inplace_pattern = rf'\(\s*"[^"]*{re.escape(inplace_op)}[^"]*"\s*,'
            if re.search(inplace_pattern, wt_content):
                # Reload to check current state
                with open(repo_yaml) as f:
                    current_data = yaml.safe_load(f)
                current_ids = [o.get("id") for o in current_data.get("ops", [])]
                if inplace_id not in current_ids:
                    inplace_entry = {
                        "id": inplace_id,
                        "description": f"The in-place version of `{op_id}()`.",
                        "for": [inplace_op],
                        "labels": ["aten", "KernelGen"],
                        "kind": ["Math"],
                        "stages": [{"alpha": "5.4"}],
                    }
                    _insert_yaml_entry(inplace_entry, repo_yaml, inplace_id, current_ids, dry_run)
                    ok(f"_FULL_CONFIG 注册了 inplace 变体，已生成独立 yaml 条目: {inplace_id}")


def _insert_yaml_entry(entry, repo_yaml, entry_id, existing_ids, dry_run):
    """Insert a single yaml entry in alphabetical order."""
    if entry_id in existing_ids:
        ok(f"yaml 已包含 id: {entry_id}，跳过")
        return

    with open(repo_yaml) as f:
        yaml_lines = f.readlines()

    insert_line = len(yaml_lines)
    i = 0
    while i < len(yaml_lines):
        match = re.match(r"\s*-\s*id:\s*(\S+)", yaml_lines[i])
        if match:
            existing_id = match.group(1)
            if entry_id < existing_id:
                insert_line = i
                break
        i += 1

    new_lines = []
    new_lines.append(f"  - id: {entry['id']}\n")
    desc = entry.get("description", "").strip()
    if "\n" in desc or len(desc) > 60:
        new_lines.append("    description: |\n")
        for dline in desc.split("\n"):
            new_lines.append(f"      {dline.strip()}\n")
    else:
        new_lines.append(f"    description: {desc}\n")
    new_lines.append("    for:\n")
    for item in entry.get("for", []):
        new_lines.append(f"      - {item}\n")
    new_lines.append("    labels:\n")
    for label in entry.get("labels", ["aten", "KernelGen"]):
        new_lines.append(f"      - {label}\n")
    new_lines.append("    kind:\n")
    for kind in entry.get("kind", ["Math"]):
        new_lines.append(f"      - {kind}\n")
    new_lines.append("    stages:\n")
    stages = entry.get("stages", [{"alpha": "5.4"}])
    if isinstance(stages, list):
        for s in stages:
            if isinstance(s, dict):
                for k, v in s.items():
                    new_lines.append(f"      - {k}: '{v}'\n")
    elif isinstance(stages, dict):
        for k, v in stages.items():
            new_lines.append(f"      - {k}: '{v}'\n")

    yaml_lines[insert_line:insert_line] = new_lines
    ok(f"yaml 插入 id: {entry_id} 在行 {insert_line + 1}")

    if dry_run:
        ok(f"[DRY] operators.yaml 将被更新 ({entry_id})")
    else:
        with open(repo_yaml, "w") as f:
            f.writelines(yaml_lines)
        ok(f"operators.yaml 已更新 ({entry_id})")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description="从 worktree 自动提取算子代码")
    parser.add_argument("operator", help="算子名称")
    parser.add_argument(
        "--repo-dir",
        default=os.environ.get("FLAGGEMS_REPO", DEFAULT_REPO),
    )
    parser.add_argument("--dry-run", action="store_true", help="只预览不写入")
    args = parser.parse_args()

    op = args.operator
    op_id = get_op_id(op)
    module_name = get_module_name(op)
    repo = os.path.abspath(args.repo_dir)
    worktree = os.path.join(repo, f".worktrees/gen-{op}")
    if is_max_pool2d_with_indices_backward(op):
        worktree = prepare_max_pool2d_with_indices_backward_source(repo)

    print(f"{Colors.BOLD}从 worktree 提取: {op}{Colors.END}")
    print(f"worktree: {worktree}")
    print(f"repo: {repo}")

    if not os.path.isdir(worktree):
        fatal(f"worktree 不存在: {worktree}")

    extract_kernel(op, worktree, repo, args.dry_run)
    extract_test(op, worktree, repo, args.dry_run)
    extract_benchmark(op, worktree, repo, args.dry_run)
    insert_ops_init(op, worktree, repo, args.dry_run)
    insert_full_config(op, worktree, repo, args.dry_run)
    insert_operators_yaml(op, worktree, repo, args.dry_run)

    print(f"\n{Colors.OK}{Colors.BOLD}✓ 6 个文件已准备完毕{Colors.END}")
    print(f"  src/flag_gems/ops/{module_name}.py")
    print(f"  src/flag_gems/ops/__init__.py")
    print(f"  src/flag_gems/__init__.py")
    print(f"  tests/test_{op_id}.py")
    print(f"  benchmark/test_{op_id}.py")
    print(f"  conf/operators.yaml")
    print(f"\n  接下来运行: CUDA_VISIBLE_DEVICES=<N> python scripts/submit_operator.py {op}")


if __name__ == "__main__":
    main()
