#!/usr/bin/env python3
"""Static quality gate for generated FlagGems worktree operators.

This script intentionally checks only deterministic red flags. The quality-gate
subagent must still read the code and apply the rules in agents/20-quality-gate.md.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from op_naming import resolve_op  # noqa: E402


class Gate:
    def __init__(self) -> None:
        self.errors: list[str] = []
        self.warnings: list[str] = []

    def error(self, msg: str) -> None:
        self.errors.append(msg)
        print(f"ERROR: {msg}")

    def warn(self, msg: str) -> None:
        self.warnings.append(msg)
        print(f"WARN: {msg}")

    def ok(self, msg: str) -> None:
        print(f"OK: {msg}")


def load_context(path: str) -> dict:
    p = Path(path).expanduser().resolve()
    if not p.is_file():
        raise SystemExit(f"context file not found: {p}")
    return json.loads(p.read_text())


def read(path: Path) -> str:
    try:
        return path.read_text()
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="replace")


def find_file(root: Path, directory: str, op_id: str) -> Path | None:
    exact = root / directory / f"test_{op_id}.py"
    if exact.is_file():
        return exact
    candidates = sorted((root / directory).glob("*.py")) if (root / directory).is_dir() else []
    mark = f"pytest.mark.{op_id}"
    for path in candidates:
        if mark in read(path):
            return path
    return None


def check_kernel(gate: Gate, path: Path, op: str, op_id: str) -> None:
    if not path.is_file():
        gate.error(f"kernel file missing: {path}")
        return
    text = read(path)
    if not text.startswith("# Generated by KernelGen"):
        gate.error("kernel first line must be KernelGen header")
    else:
        gate.ok("kernel has KernelGen header")
    if "print(" in text:
        gate.error("kernel contains print(); use logging")
    if "@triton.jit" not in text and "pointwise_dynamic" not in text:
        gate.error("kernel has no visible Triton/pointwise_dynamic implementation")

    stripped_lines = [line.split("#", 1)[0] for line in text.splitlines()]
    body = "\n".join(stripped_lines)
    dangerous = [f"torch.{op}", f"torch.{op_id}", "torch.nn.functional"]
    for token in dangerous:
        if re.search(rf"\b{re.escape(token)}\s*\(", body) or (token == "torch.nn.functional" and token in body):
            gate.error(f"kernel appears to use torch fallback: {token}")

    funcs = re.findall(r"^\s*def\s+(\w+)\s*\(", text, flags=re.MULTILINE)
    duplicates = sorted({f for f in funcs if funcs.count(f) > 1})
    if duplicates:
        gate.error(f"duplicate function definitions: {duplicates}")

    for stub in re.findall(r"@use_tl_extra\s+(?:@\w[\w.]*\s+)*def\s+(\w+)\s*\(", text, flags=re.MULTILINE):
        calls = re.findall(rf"(?<!def\s)\b{re.escape(stub)}\s*\(", text)
        if not calls:
            gate.error(f"unused @use_tl_extra stub: {stub}")


def check_test(gate: Gate, path: Path | None, op_id: str) -> None:
    if path is None:
        gate.error(f"test file not found for mark {op_id}")
        return
    text = read(path)
    if f"pytest.mark.{op_id}" not in text:
        gate.error(f"test mark mismatch: expected pytest.mark.{op_id}")
    if "from . import accuracy_utils as utils" not in text:
        gate.error("test must use relative accuracy_utils import")
    if "utils.to_reference" not in text and "to_reference" not in text:
        gate.warn("test does not visibly use to_reference(); verify reference path manually")
    if "rtol=" in text:
        gate.error("gems_assert_close does not accept rtol")
    for token in ("print(", "QUICK_MODE", "vendor_name"):
        if token in text:
            gate.error(f"test contains forbidden token: {token}")


def check_benchmark(gate: Gate, path: Path | None, op_id: str) -> None:
    if path is None:
        gate.error(f"benchmark file not found for mark {op_id}")
        return
    text = read(path)
    if f"pytest.mark.{op_id}" not in text:
        gate.error(f"benchmark mark mismatch: expected pytest.mark.{op_id}")
    if f'op_name="{op_id}"' not in text and f"op_name='{op_id}'" not in text:
        gate.warn(f"benchmark op_name={op_id!r} not found; verify multi-overload alignment manually")
    if "from . import base" not in text:
        gate.error("benchmark must use benchmark/base.py wrappers")
    if "if __name__" in text:
        gate.error("benchmark must be pytest-driven, not a standalone script")


def main() -> None:
    parser = argparse.ArgumentParser(description="Static quality gate for one generated worktree")
    parser.add_argument("--context", required=True)
    parser.add_argument("--op", required=True, help="normalized operator name")
    args = parser.parse_args()

    ctx = load_context(args.context)
    names = resolve_op(args.op)
    root = Path(ctx["worktree_root"]).resolve() / f"gen-{args.op}"
    if not root.is_dir():
        alt = Path(ctx["worktree_root"]).resolve() / f"gen-{names.op_id}"
        root = alt if alt.is_dir() else root
    if not root.is_dir():
        raise SystemExit(f"worktree not found: {root}")

    gate = Gate()
    check_kernel(gate, root / "src" / "flag_gems" / "ops" / f"{names.module}.py", args.op, names.op_id)
    check_test(gate, find_file(root, "tests", names.op_id), names.op_id)
    check_benchmark(gate, find_file(root, "benchmark", names.op_id), names.op_id)

    print(json.dumps({"errors": gate.errors, "warnings": gate.warnings}, ensure_ascii=False, indent=2))
    if gate.errors:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
